server:  
  port: ${PORT:3333}

spring:
  application:
    name: customer-service
  profiles : default
#  boot:
#    admin:
#      client:
#        url:
#        - http://myadmin-console-india:9001
    

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
      
eureka:        
  client:
    serviceUrl:
      defaultZone: http://eureka-south-india:7001/eureka/

      
 
      
  
      
           
 
 
